---
# tasks file for haproxy
- name: install haproxy
  yum:
   name: haproxy
   state: latest

- name: start and enable haproxy
  systemd:
   name: haproxy
   state: started
   enabled: true

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false

- name: Set HAProxy version.
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: create dir
  file:
   path: /etc/haproxy/backup/
   state: directory

- name: backup original haproxy
  copy:
   src: /etc/haproxy/haproxy.cfg
   dest: /etc/haproxy/backup/haproxy.cfg.orig
   remote_src: true

- name: configure haproxy.cfg
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
  notify:
   - restart haproxy
